INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'in28minutes' ,'GET AWS CERTIFICATED',  CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'in28minutes' ,'GET AZURE',  CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'in28minutes' ,'GET GCP',  CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'in28minutes' ,'GET DEVOPS',  CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10005, 'in28minutes' ,'LEARN SPRING',  CURRENT_DATE(), false);
